/* AUTOMATICALLY GENERATED VERILOG-2001 SOURCE CODE.
** GENERATED BY CLASH 0.99.3. DO NOT MODIFY.
*/
module DataSender
    ( // Inputs
      input  clk // clock
    , input  rst // asynchronous reset: active high
    , input [39:0] dataIn 
    , input  transmission_done 
    , input  transmission_started 

      // Outputs
    , output wire [7:0] dataOut 
    );
  wire [104:0] \#tup_app_arg ;
  wire [39:0] ds1;
  reg [104:0] state;
  wire [41:0] eta1;

  assign eta1 = {dataIn
                ,transmission_done
                ,transmission_started};

  DataSender_updateState DataSender_updateState_tup_app_arg
    ( .\#case_alt  (\#tup_app_arg )
    , .ds (eta1)
    , .state (state) );

  assign dataOut = $unsigned(ds1);

  assign ds1 = state[104:65];

  // register begin
  always @(posedge clk or posedge rst) begin : DataSender_register
    if (rst) begin
      state <= {40'd0,{1'b0,64'bxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx}};
    end else begin
      state <= \#tup_app_arg ;
    end
  end
  // register end
endmodule

