/* AUTOMATICALLY GENERATED VERILOG-2001 SOURCE CODE.
** GENERATED BY CLASH 0.99.3. DO NOT MODIFY.
*/
module SignalAnalyser
    ( // Inputs
      input  clk // clock
    , input  rst // asynchronous reset: active high
    , input [7:0] dataIn 

      // Outputs
    , output wire [31:0] dataTime 
    , output wire [7:0] dataOut 
    , output wire  newData 
    );
  wire [72:0] \#tup_app_arg ;
  reg  \#tup_app_arg_0 ;
  wire [7:0] ds3;
  wire [31:0] ds4;
  reg [72:0] state;
  wire [0:0] ds5;
  wire [7:0] \#tup_app_arg_fun_arg ;
  wire signed [63:0] \#i ;
  wire signed [63:0] \#i_0 ;
  wire [40:0] x;

  assign x = {ds4,ds3,\#tup_app_arg_0 };

  assign \#tup_app_arg_fun_arg  = dataIn;

  SignalAnalyser_signalAnalyserT_supdateState SignalAnalyser_signalAnalyserT_supdateState_tup_app_arg
    ( .result (\#tup_app_arg )
    , .ds (\#tup_app_arg_fun_arg )
    , .state (state) );

  assign \#i  = 64'sd0;

  assign \#i_0  = 64'sd1;

  always @(*) begin
    case(ds5)
      1'b0 : \#tup_app_arg_0  = 1'b0;
      default : \#tup_app_arg_0  = 1'b1;
    endcase
  end

  assign ds3 = state[40:33];

  assign ds4 = state[32:1];

  // register begin
  always @(posedge clk or posedge rst) begin : SignalAnalyser_register
    if (rst) begin
      state <= {32'd0,8'd0,32'd0,1'd0};
    end else begin
      state <= \#tup_app_arg ;
    end
  end
  // register end

  assign ds5 = state[0:0];

  assign dataTime = x[40:9];

  assign dataOut = x[8:1];

  assign newData = x[0:0];
endmodule

