/* AUTOMATICALLY GENERATED VERILOG-2001 SOURCE CODE.
** GENERATED BY CLASH 0.99.3. DO NOT MODIFY.
*/
module SignalAnalyser_signalAnalyserT_supdateState
    ( // Inputs
      input [7:0] ds 
    , input [72:0] state 

      // Outputs
    , output wire [72:0] result 
    );
  reg [31:0] \#app_arg ;
  reg [0:0] \#app_arg_0 ;
  wire [7:0] newData1;
  wire  trans;
  wire [31:0] ds1;
  wire [31:0] ds3;
  wire [7:0] ds2;

  assign result = {ds1 + 32'd1
                  ,newData1
                  ,\#app_arg 
                  ,\#app_arg_0 };

  always @(*) begin
    if(trans)
      \#app_arg  = ds1;
    else
      \#app_arg  = ds3;
  end

  always @(*) begin
    if(trans)
      \#app_arg_0  = 1'd1;
    else
      \#app_arg_0  = 1'd0;
  end

  assign newData1 = ds;

  assign trans = newData1 != ds2;

  assign ds1 = state[72:41];

  assign ds3 = state[32:1];

  assign ds2 = state[40:33];
endmodule

