/* AUTOMATICALLY GENERATED VERILOG-2001 SOURCE CODE.
** GENERATED BY CLASH 0.99.3. DO NOT MODIFY.
*/
module Spi_updateStateData
    ( // Inputs
      input [26:0] state 
    , input [9:0] ds 

      // Outputs
    , output reg [26:0] \#case_alt  
    );
  wire [7:0] ds2;
  wire  \input ;
  wire [7:0] \#app_arg ;
  wire [7:0] ds3;
  reg [7:0] \#app_arg_0 ;
  wire [10:0] ds1;
  wire  \#app_arg_0_selection_res ;

  assign ds2 = state[15:8];

  assign \input  = ds[8:8];

  assign \#app_arg  = ds2 << (64'sd1);

  assign ds3 = state[7:0];

  assign \#app_arg_0_selection_res  = \input  == (1'b0);

  always @(*) begin
    if(\#app_arg_0_selection_res )
      \#app_arg_0  = \#app_arg  + 8'd0;
    else
      \#app_arg_0  = \#app_arg  + 8'd1;
  end

  assign ds1 = state[26:16];

  always @(*) begin
    case(ds1[10:8])
      3'b010 : \#case_alt  = {ds1,\#app_arg_0 ,ds3};
      default : \#case_alt  = state;
    endcase
  end
endmodule

