/* AUTOMATICALLY GENERATED VERILOG-2001 SOURCE CODE.
** GENERATED BY CLASH 0.99.3. DO NOT MODIFY.
*/
module Spi_output_r
    ( // Inputs
      input [26:0] ds 
    , input [9:0] \input  

      // Outputs
    , output wire [11:0] \#case_alt  
    );
  reg  \#app_arg ;
  reg  \#case_alt_0 ;
  wire [7:0] a1;
  reg  \#app_arg_0 ;
  reg  \#app_arg_1 ;
  wire [10:0] ds1;
  wire [7:0] ds2;
  wire [7:0] ds3;
  wire signed [63:0] \#i ;
  wire signed [63:0] \#i_0 ;
  wire signed [63:0] \#i_1 ;
  wire signed [63:0] \#i_2 ;
  wire signed [63:0] \#i_3 ;
  wire signed [63:0] \#i_4 ;
  wire signed [63:0] \#i_5 ;
  wire signed [63:0] \#i_6 ;
  wire [7:0] \#bv ;

  assign \#i  = 64'sd1;

  assign \#i_0  = 64'sd0;

  always @(*) begin
    case(ds1[10:8])
      3'b001 : \#app_arg  = 1'b1;
      default : \#app_arg  = 1'b0;
    endcase
  end

  assign \#i_1  = 64'sd1;

  assign \#i_2  = 64'sd0;

  always @(*) begin
    case(a1)
      8'd0 : \#case_alt_0  = 1'b1;
      default : \#case_alt_0  = 1'b0;
    endcase
  end

  assign a1 = ds1[7:0];

  assign \#i_3  = 64'sd0;

  always @(*) begin
    case(ds1[10:8])
      3'b010 : \#app_arg_0  = \#case_alt_0 ;
      default : \#app_arg_0  = 1'b0;
    endcase
  end

  assign \#i_4  = 64'sd1;

  assign \#i_5  = 64'sd1;

  assign \#i_6  = 64'sd0;

  always @(*) begin
    case(ds1[10:8])
      3'b000 : \#app_arg_1  = 1'b1;
      3'b001 : \#app_arg_1  = 1'b1;
      default : \#app_arg_1  = 1'b0;
    endcase
  end

  assign \#bv  = (ds3);

  assign \#case_alt  = {ds2
                       ,\#app_arg 
                       , \#bv [8-1] 
                       ,\#app_arg_0 
                       ,\#app_arg_1 };

  assign ds1 = ds[26:16];

  assign ds2 = ds[15:8];

  assign ds3 = ds[7:0];
endmodule

