/* AUTOMATICALLY GENERATED VERILOG-2001 SOURCE CODE.
** GENERATED BY CLASH 0.99.3. DO NOT MODIFY.
*/
module Spi_nextStep
    ( // Inputs
      input [26:0] ds 
    , input [9:0] ds1 

      // Outputs
    , output reg [10:0] \#case_alt  
    );
  wire [7:0] \#app_arg ;
  wire  clk1;
  wire [7:0] amount;
  wire [7:0] amount_0;
  wire [7:0] amount_1;
  wire [7:0] amount_2;
  reg [10:0] \#case_alt_0 ;
  wire  \#case_scrut ;
  wire [10:0] ds2;
  reg [10:0] \#case_alt_1 ;
  reg [10:0] \#case_alt_2 ;
  reg [10:0] \#case_alt_3 ;
  reg [10:0] \#case_alt_4 ;
  reg [10:0] \#case_alt_5 ;
  wire signed [63:0] \#i ;

  assign \#app_arg  = amount_2 + 8'd1;

  assign clk1 = ds1[9:9];

  assign amount = ds2[7:0];

  assign amount_0 = ds2[7:0];

  assign amount_1 = ds2[7:0];

  assign amount_2 = ds2[7:0];

  always @(*) begin
    if(\#case_scrut )
      \#case_alt_0  = {3'b010,\#app_arg };
    else
      \#case_alt_0  = {3'b100,\#app_arg };
  end

  assign \#i  = 64'sd1;

  assign \#case_scrut  = clk1 == 1'b1;

  assign ds2 = ds[26:16];

  always @(*) begin
    case(amount_2)
      8'd7 : \#case_alt_1  = {3'b001,8'bxxxxxxxx};
      default : \#case_alt_1  = \#case_alt_0 ;
    endcase
  end

  always @(*) begin
    if(\#case_scrut )
      \#case_alt_2  = {3'b010,amount};
    else
      \#case_alt_2  = ds2;
  end

  always @(*) begin
    if(\#case_scrut )
      \#case_alt_3  = ds2;
    else
      \#case_alt_3  = {3'b101,amount_0};
  end

  always @(*) begin
    if(\#case_scrut )
      \#case_alt_4  = {3'b011,amount_1};
    else
      \#case_alt_4  = {3'b101,amount_1};
  end

  always @(*) begin
    if(\#case_scrut )
      \#case_alt_5  = {3'b010,8'd0};
    else
      \#case_alt_5  = {3'b000,8'bxxxxxxxx};
  end

  always @(*) begin
    case(ds2[10:8])
      3'b010 : \#case_alt  = \#case_alt_4 ;
      3'b011 : \#case_alt  = \#case_alt_3 ;
      3'b100 : \#case_alt  = \#case_alt_2 ;
      3'b101 : \#case_alt  = \#case_alt_1 ;
      default : \#case_alt  = \#case_alt_5 ;
    endcase
  end
endmodule

